import type { Avatar, Template, SystemFlow, TelemetryData } from '@/types';
import type { ReactNode } from 'react';
import { Zap, Brain, Users, Radio, FileText, Activity } from 'lucide-react';

const avatarImages = [
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
];

export const mockAvatars: Avatar[] = [
  {
    id: 'avatar-1',
    name: 'Dr. Elena Vásquez',
    role: 'Chief Medical Officer',
    image: avatarImages[0],
    category: 'Healthcare',
    price: '$299/mo',
    trust: 98,
    status: 'active',
    isSynthetic: true,
    promptConfig: { tone: 'professional', specialty: 'cardiology' }
  },
  {
    id: 'avatar-2',
    name: 'Marcus Chen',
    role: 'Tech Evangelist',
    image: avatarImages[1],
    category: 'Technology',
    price: '$199/mo',
    trust: 95,
    status: 'active',
    isSynthetic: true,
    promptConfig: { tone: 'visionary', specialty: 'ai' }
  },
  {
    id: 'avatar-3',
    name: 'Sarah Mitchell',
    role: 'Real Estate Expert',
    image: avatarImages[2],
    category: 'Finance',
    price: '$249/mo',
    trust: 92,
    status: 'active',
    isSynthetic: true,
    promptConfig: { tone: 'trustworthy', specialty: 'luxury' }
  },
  {
    id: 'avatar-4',
    name: 'James Rodriguez',
    role: 'Fitness Coach',
    image: avatarImages[3],
    category: 'Health',
    price: '$149/mo',
    trust: 89,
    status: 'active',
    isSynthetic: true,
    promptConfig: { tone: 'energetic', specialty: 'performance' }
  },
  {
    id: 'avatar-5',
    name: 'Aisha Patel',
    role: 'Legal Consultant',
    image: avatarImages[4],
    category: 'Legal',
    price: '$399/mo',
    trust: 97,
    status: 'active',
    isSynthetic: true,
    promptConfig: { tone: 'precise', specialty: 'corporate' }
  },
  {
    id: 'avatar-6',
    name: 'David Kim',
    role: 'Startup Mentor',
    image: avatarImages[5],
    category: 'Business',
    price: '$299/mo',
    trust: 94,
    status: 'active',
    isSynthetic: true,
    promptConfig: { tone: 'inspiring', specialty: 'entrepreneurship' }
  }
];

const storedAvatars = [...mockAvatars];

export const getAvatars = async (): Promise<Avatar[]> => {
  return storedAvatars;
};

export const updateAvatarAsset = async (
  id: string,
  field: 'image' | 'videoUrl' | 'avatar_hq' | 'video_preview_es' | 'video_preview_en',
  value: string,
  file?: File
): Promise<void> => {
  const avatar = storedAvatars.find(a => a.id === id);
  if (avatar) {
    if (!avatar.media) {
      avatar.media = {};
    }
    if (field === 'avatar_hq') {
      avatar.media.avatar_hq = value;
    } else if (field === 'video_preview_es') {
      avatar.media.video_preview_es = value;
    } else if (field === 'video_preview_en') {
      avatar.media.video_preview_en = value;
    } else {
      (avatar as any)[field] = value;
    }
  }
};

export const mockTemplates: Template[] = [
  {
    id: 'template-1',
    title: 'SaaS Product Launch',
    category: 'Marketing',
    description: 'Launch your software product with maximum impact',
    price: 497,
    metrics: { roi: '340%', time: '2 hours' },
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80',
    bestseller: true,
    includes: ['30-second video', '3 platform versions', 'Script & storyboard']
  },
  {
    id: 'template-2',
    title: 'Real Estate Showcase',
    category: 'Real Estate',
    description: 'Property tours that convert leads to buyers',
    price: 297,
    metrics: { roi: '280%', time: '1 hour' },
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80',
    bestseller: false,
    includes: ['Property tour video', 'Agent intro', 'Call-to-action overlay']
  },
  {
    id: 'template-3',
    title: 'Course Creator Promo',
    category: 'Education',
    description: 'Generate enrollments for your online course',
    price: 397,
    metrics: { roi: '420%', time: '90 mins' },
    image: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&q=80',
    bestseller: true,
    includes: ['Teaser video', 'Testimonial slides', 'Enrollment CTA']
  },
  {
    id: 'template-4',
    title: 'Medical Practice Intro',
    category: 'Healthcare',
    description: 'Build trust with prospective patients',
    price: 349,
    metrics: { roi: '310%', time: '75 mins' },
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    bestseller: false,
    includes: ['Doctor introduction', 'Facility tour', 'Service overview']
  },
  {
    id: 'template-5',
    title: 'Fitness Transformation',
    category: 'Health',
    description: 'Showcase results and attract new clients',
    price: 247,
    metrics: { roi: '250%', time: '45 mins' },
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80',
    bestseller: false,
    includes: ['Transformation video', 'Client testimonial', 'Free consultation CTA']
  }
];

const iconMap: Record<string, ReactNode> = {
  Zap: <Zap className="w-5 h-5" />,
  Brain: <Brain className="w-5 h-5" />,
  Users: <Users className="w-5 h-5" />,
  Radio: <Radio className="w-5 h-5" />,
  FileText: <FileText className="w-5 h-5" />,
  Activity: <Activity className="w-5 h-5" />
};

export const mockSystemFlows: SystemFlow[] = [
  {
    id: 'f_eth_zero',
    title: 'David G.',
    tag: 'DOGFOODING',
    headerLabel: 'EtherAgent Core Instance',
    icon: iconMap.Brain,
    description: 'Primer influencer sintético creado mediante prompt engineering - Dogfooding del propio founder',
    steps: [
      {
        id: 'david_phase_1',
        title: 'Phase 1: Hyper-Realistic Image Synthesis',
        titleEn: 'Phase 1: Hyper-Realistic Image Synthesis',
        status: 'completed',
        icon: iconMap.Brain,
        description: 'Genera imagen base del influencer con especificaciones exactas para máxima autoridad C-Suite',
        descriptionEn: 'Generate base image of the influencer with exact specifications for maximum C-Suite authority',
        details: [
          '<subject_lock> Male, 32-35 years old, sharp angular jawline, piercing deep-brown eyes, meticulously groomed subtle stubble, looking directly into the lens with predatory focus. His name is David G., EtherAI Influencer, tech founder archetype. </subject_lock>',
          '<attire> Pure minimalist luxury. Premium black turtleneck (Steve Jobs/Tech Founder archetype), fine merino wool fabric texture visible. Subtle "EtherAI Influencer" embossed in ultra-fine matte silver threading on the left chest, barely visible, high-end luxury finish. NO logos, NO embroidery on clothing except subtle brand mark. </attire>',
          '<background> Absolute minimalism. A solid, seamless dark charcoal/pure black studio backdrop. Zero distractions, empty void. </background>',
          '<lighting> Dramatic studio chiaroscuro. Key light: Soft 45-degree diffused white illuminating the face. Rim light: Sharp, vibrant Emerald Green (#10B981) edge light hitting the left shoulder and jawline, separating the subject from the dark void to anchor the EtherAgent brand identity. </lighting>',
          '<camera_specs> Shot on ARRI Alexa 65, 85mm portrait lens. Razor-sharp focus on the eyes. </camera_specs>',
          '<texture_fidelity> Hyper-detailed skin pores, micro-imperfections, highly realistic skin specular reflection. </texture_fidelity>',
          '<negative_prompt> 3d render, CGI, plastic, cartoon, windows, office, furniture, messy background, text, watermarks, casual clothing. </negative_prompt>'
        ]
      },
      {
        id: 'david_phase_2',
        title: 'Phase 2: Neural Motion & Kinesics',
        titleEn: 'Phase 2: Neural Motion & Kinesics',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura movimientos corporales y expresiones faciales para proyectar dominio absoluto',
        descriptionEn: 'Configure body movements and facial expressions to project absolute dominance',
        details: [
          '# MOTION BASE STATE',
          '<motion_vectors>',
          '- Base state: High authority, static posture',
          '- Anchor head at center frame',
          '- Limit horizontal sway to ±5 degrees',
          '- Subtle breathing rhythm (2s cycle)',
          '- Weight shift: Slight forward lean when delivering key value propositions',
          '</motion_vectors>',
          '',
          '# FACIAL EXPRESSIONS',
          '<facial_expressions>',
          '- Action 1: Assertive micro-nod when delivering core value proposition (00:08)',
          '- Action 2: Minimal blinking (target: 3-4 blinks per 10 seconds) to project dominance',
          '- Action 3: Subtle jaw tightening on key emphasis moments',
          '- Micro-expression: Controlled certainty - no smiling, no uncertainty',
          '</facial_expressions>',
          '',
          '# KINESICS GUIDELINES',
          '- Eye contact: Unbroken, predatory focus throughout',
          '- Gestures: Minimal, purposeful, confined to lower third of frame',
          '- Posture: Straight, commanding, chin slightly elevated'
        ]
      },
      {
        id: 'david_phase_3_es',
        title: 'Phase 3: Spanish Audio & Lip-Sync',
        titleEn: 'Phase 3: Spanish Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en español',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in Spanish',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Founder Pitch Mapping ES) </engine>',
          '<voice_profile>',
          '- Tone: Grave, pausado, cortante - autoridad absoluta',
          '- Pace: 140-150 WPM (slower than average for gravitas)',
          '- Accent: Neutral Spanish (España/LatAm)',
          '- Emotion: Dominante, disruptivo, C-Suite',
          '</voice_profile>',
          '',
          '# SPANISH SCRIPT (FULL 18s)',
          '<spanish_script>',
          '[00:00-00:03] APERTURA - Mirada penetrante a la cámara',
          '"Contratar humanos para tareas repetitivas es un error financiero."',
          '',
          '[00:03-00:08] EL DOLOR - Tono analítico',
          '"Tu costo de adquisición sube, mientras tu velocidad de cierre baja. [0.3s pause] Es una fuga de capital."',
          '',
          '[00:08-00:13] LA SOLUCIÓN - Cambio a tono expansivo y seguro',
          '"EtherAgent OS no es un software. [0.3s pause] Es una infraestructura neuronal que clona a tus mejores vendedores."',
          '',
          '[00:13-00:18] CIERRE - Call to Action definitivo',
          '"Automatiza tu influencia. Domina tu nicho. [0.4s pause] Fuego a discreción."',
          '',
          '# PHONEME FOCUS',
          '- Emphasis on: "error financiero", "fuga de capital", "infraestructura neuronal"',
          '- Clean frication on "in-fra-es-truc-tu-ra"',
          '- Sharp cutoff on "fuego"',
          '</spanish_script>',
          '',
          '# 6-SECOND PREVIEW (SPANISH)',
          '<preview_spanish>',
          '"El mercado no perdona la lentitud. [0.5s pause] Despliega tu propio ejército digital con EtherAgent OS."',
          '- KEY MOMENT: Pausa dramática en "lentitud" + leve inclinación hacia adelante en "ejército digital"',
          '</preview_spanish>',
          '',
          '# BRANDING OVERLAY',
          '- Logo #10B981 latido sutil en el fondo (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/core (aparece 15.0s-18.0s)'
        ]
      },
      {
        id: 'david_phase_3_en',
        title: 'Phase 3: English Audio & Lip-Sync',
        titleEn: 'Phase 3: English Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en inglés',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in English',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Founder Pitch Mapping EN) </engine>',
          '<voice_profile>',
          '- Tone: Grave, authoritative, cutting - absolute authority',
          '- Pace: 140-150 WPM (slower than average for gravitas)',
          '- Accent: Neutral American English',
          '- Emotion: Dominant, disruptive, C-Suite',
          '</voice_profile>',
          '',
          '# ENGLISH SCRIPT (FULL 18s)',
          '<english_script>',
          '[00:00-00:03] OPENING - Penetrating gaze at camera',
          '"Hiring humans for repetitive tasks is a financial mistake."',
          '',
          '[00:03-00:08] THE PAIN - Analytical tone',
          '"Your acquisition cost goes up while your closing speed goes down. [0.3s pause] It\'s a capital leak."',
          '',
          '[00:08-00:13] THE SOLUTION - Expansive and confident tone',
          '"EtherAgent OS is not software. [0.3s pause] It\'s a neural infrastructure that clones your best salespeople."',
          '',
          '[00:13-00:18] CLOSURE - Definitive Call to Action',
          '"Automate your influence. Dominate your niche. [0.4s pause] Fire at will."',
          '',
          '# PHONEME FOCUS',
          '- Sharp articulation on "capital leak", "neural infrastructure"',
          '- Command presence on "fire at will"',
          '</english_script>',
          '',
          '# 6-SECOND PREVIEW (ENGLISH)',
          '<preview_english>',
          '"The market doesn\'t forgive slowness. [0.5s pause] Deploy your own digital army with EtherAgent OS."',
          '- KEY MOMENT: Dramatic pause at "slowness" + slight lean forward at "digital army"',
          '</preview_english>',
          '',
          '# BRANDING OVERLAY',
          '- Logo #10B981 subtle pulse in background (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/core (appears 15.0s-18.0s)'
        ]
      },
      {
        id: 'david_phase_4',
        title: 'Phase 4: The EtherClaw Master Payload',
        titleEn: 'Phase 4: The EtherClaw Master Payload',
        status: 'completed',
        icon: iconMap.FileText,
        description: 'Genera el payload maestro final compilando todos los activos para renderizado profesional',
        descriptionEn: 'Generate final master payload compiling all assets for professional rendering',
        details: [
          '# COMPILER SYSTEM',
          '{',
          '  "system": "EtherAgent_Core_Compiler",',
          '  "target_niche": "C-Suite_Founders",',
          '  "instance_type": "Dogfooding_Core",',
          '',
          '  "visual_seed": {',
          '    "base_prompt": "[Phase 1 Output]",',
          '    "brand_color_hex": "#10B981",',
          '    "rim_light_fidelity": "strict"',
          '  },',
          '',
          '  "audio_seed": {',
          '    "voice_model": "EtherClaw_V3_Founder",',
          '    "languages": ["es-ES", "en-US"],',
          '    "scripts": {',
          '      "spanish": "[Phase 3ES Output]",',
          '      "english": "[Phase 3EN Output]"',
          '    }',
          '  },',
          '',
          '  "motion_seed": {',
          '    "kinesics_profile": "High_Authority",',
          '    "facial_expressions": "[Phase 2 Output]"',
          '  },',
          '',
          '  "compiler_directives": [',
          '    "Enforce perfect lip-sync at 99%+ accuracy",',
          '    "Maintain emerald rim light fidelity throughout",',
          '    "Preserve micro-expression realism",',
          '    "Zero frame drops during branding overlays",',
          '    "Render at minimum 30fps for smooth playback"',
          '  ],',
          '',
          '  "output_config": {',
          '    "formats": ["mp4", "webm"],',
          '    "resolutions": ["1080p", "4k"],',
          '    "aspect_ratios": ["9:16", "4:5", "1:1"]',
          '  }',
          '}',
          '',
          '# RENDER PRIORITY',
          '- Primary: 9:16 (Vertical/Stories)',
          '- Secondary: 4:5 (Feed/Instagram)',
          '- Tertiary: 1:1 (Square)',
          '',
          '# DEPLOYMENT TARGETS',
          '- etheragent.io/core (CTA principal)',
          '- Social media: LinkedIn, Instagram, YouTube Shorts',
          '- Email marketing: High-ticket nurturing sequences'
        ]
      }
    ],
    media: {
      avatar_hq: '/assets/images/david_hq.webp',
      video_preview_es: '/assets/videos/david_6s_es.mp4',
      video_preview_en: '/assets/videos/david_6s_en.mp4',
      video_full_es: '/assets/videos/david_18s_es.mp4',
      video_full_en: '/assets/videos/david_18s_en.mp4'
    }
  },
  {
    id: 'f_marcus',
    title: 'Marcus V.',
    tag: 'ENTERPRISE',
    headerLabel: 'C-Suite Executive',
    icon: iconMap.Brain,
    description: 'Ejecutivo corporativo para pitches enterprise - Nicho FinTech/Ventas High-Ticket',
    steps: [
      {
        id: 'marcus_phase_1',
        title: 'Phase 1: Hyper-Realistic Image Synthesis',
        titleEn: 'Phase 1: Hyper-Realistic Image Synthesis',
        status: 'completed',
        icon: iconMap.Brain,
        description: 'Genera imagen base del ejecutivo corporativo con especificaciones exactas para nicho FinTech',
        descriptionEn: 'Generate base image of the corporate executive with exact specifications for FinTech niche',
        details: [
          '<subject_lock> Male, 38-42 years old, Asian descent, razor-sharp jawline, intense and calculating gaze. His name is Marcus V., EtherAI Influencer, FinTech executive archetype. </subject_lock>',
          '<attire> Bespoke charcoal grey pinstripe suit, crisp white shirt, no tie. Wall Street / FinTech executive aesthetic. Subtle "EtherAI Influencer" embossed in ultra-fine matte silver threading on the left lapel, barely visible, high-end luxury finish. NO logos on clothing except subtle "EtherAI Influencer" brand mark. </attire>',
          '<background> Absolute minimalism. A solid, seamless dark charcoal/pure black studio backdrop. Zero distractions, empty void. </background>',
          '<lighting> Dramatic studio chiaroscuro. Key light: Soft 45-degree diffused white illuminating the face. Rim light: Sharp, vibrant Emerald Green (#10B981) edge light hitting the right shoulder and jawline, separating the subject from the dark void to anchor the EtherAgent brand identity. </lighting>',
          '<camera_specs> Shot on ARRI Alexa 65, 85mm portrait lens. Razor-sharp focus on the eyes. </camera_specs>',
          '<texture_fidelity> Hyper-detailed skin pores, micro-imperfections, highly realistic skin specular reflection. </texture_fidelity>',
          '<negative_prompt> 3d render, CGI, plastic, cartoon, windows, office, furniture, messy background, city lights, warm lighting, casual clothing, text on clothing, watermarks. </negative_prompt>'
        ]
      },
      {
        id: 'marcus_phase_2',
        title: 'Phase 2: Neural Motion & Kinesics',
        titleEn: 'Phase 2: Neural Motion & Kinesics',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura movimientos corporales y expresiones faciales para proyectar poder institucional',
        descriptionEn: 'Configure body movements and facial expressions to project institutional power',
        details: [
          '# MOTION BASE STATE',
          '<motion_vectors>',
          '- Base state: Absolute stillness - proyecta poder y control',
          '- Anchor head at center frame',
          '- Zero horizontal sway - completo estatismo',
          '- Subtle breathing (3s cycle for gravitas)',
          '- Weight shift: None - mantener poder static',
          '</motion_vectors>',
          '',
          '# FACIAL EXPRESSIONS',
          '<facial_expressions>',
          '- Action 1: Intense, unbroken eye contact throughout entire delivery',
          '- Action 2: Micro-expression of calculated certainty at 00:03 (slight nod)',
          '- Action 3: Zero blinking target (2-3 blinks per 15 seconds)',
          '- Action 4: Subtle jaw clench on "High-Ticket" for emphasis',
          '- Micro-expression: Cold calculation - no warmth, no hesitation',
          '</facial_expressions>',
          '',
          '# KINESICS GUIDELINES',
          '- Eye contact: Unbreakable, predatory stare',
          '- Gestures: NONE - completa quietud corporal',
          '- Posture: Perfectly upright, chair-bound authority',
          '- Movement: Only lips and eyes - absolute control'
        ]
      },
      {
        id: 'marcus_phase_3_es',
        title: 'Phase 3: Spanish Audio & Lip-Sync',
        titleEn: 'Phase 3: Spanish Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en español para mercado Latino',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in Spanish for Latin market',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Enterprise Fintech Mapping ES) </engine>',
          '<voice_profile>',
          '- Tone: Frío, calculador, corporativo - autoridad institucional',
          '- Pace: 130-145 WPM (delivery medida, estratégica)',
          '- Accent: Neutral Spanish (énfasis en vowels claros)',
          '- Emotion: Frío, implacable, ejecutivo de Wall Street',
          '</voice_profile>',
          '',
          '# SPANISH SCRIPT (FULL 18s)',
          '<spanish_script>',
          '[00:00-00:04] APERTURA - Mirada inquebrantable',
          '"Las ventas High-Ticket no dependen de la suerte. Dependen del volumen y la precisión."',
          '',
          '[00:04-00:09] EL DOLOR - Ligero movimiento de cabeza',
          '"Tus ejecutivos se agotan. Pierden leads por falta de seguimiento. [0.2s pause] Yo no."',
          '',
          '[00:09-00:15] LA SOLUCIÓN - Implacable',
          '"Fui sintetizado por EtherAgent OS para operar a nivel institucional. Contacto a 10,000 CEOs en múltiples idiomas simultáneamente."',
          '',
          '[00:15-00:18] CIERRE - Autoridad final',
          '"Escala tu facturación. Elimina la fricción humana."',
          '',
          '# PHONEME FOCUS',
          '- Sharp emphasis on: "High-Ticket", "volumen", "precisión"',
          '- Clean delivery on "10,000 CEOs"',
          '- Cut through on "fricción humana"',
          '</spanish_script>',
          '',
          '# 6-SECOND PREVIEW (SPANISH)',
          '<preview_spanish>',
          '"El capital exige velocidad. [0.5s pause] EtherAgent OS automatiza tus cierres en milisegundos."',
          '- KEY MOMENT: Parpadeo lento y deliberado en la pausa [0.5s]',
          '</preview_spanish>',
          '',
          '# BRANDING OVERLAY',
          '- Reflejo esmeralda cruzando el cristal de fondo (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/enterprise (aparece 15.0s-18.0s)'
        ]
      },
      {
        id: 'marcus_phase_3_en',
        title: 'Phase 3: English Audio & Lip-Sync',
        titleEn: 'Phase 3: English Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en inglés para mercado USA',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in English for USA market',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Enterprise Fintech Mapping EN) </engine>',
          '<voice_profile>',
          '- Tone: Cold, calculating, corporate - institutional authority',
          '- Pace: 130-145 WPM (measured, strategic delivery)',
          '- Accent: Neutral American English (crisp vowel sounds)',
          '- Emotion: Cold, relentless, Wall Street executive',
          '</voice_profile>',
          '',
          '# ENGLISH SCRIPT (FULL 18s)',
          '<english_script>',
          '[00:00-00:04] OPENING - Unbreakable gaze',
          '"High-Ticket sales don\'t depend on luck. They depend on volume and precision."',
          '',
          '[00:04-00:09] THE PAIN - Slight head movement',
          '"Your executives burn out. They lose leads due to lack of follow-up. [0.2s pause] I don\'t."',
          '',
          '[00:09-00:15] THE SOLUTION - Relentless',
          '"I was synthesized by EtherAgent OS to operate at an institutional level. I contact 10,000 CEOs in multiple languages simultaneously."',
          '',
          '[00:15-00:18] CLOSURE - Final authority',
          '"Scale your billing. Eliminate human friction."',
          '',
          '# PHONEME FOCUS',
          '- Sharp emphasis on: "High-Ticket", "volume", "precision"',
          '- Clean delivery on "10,000 CEOs"',
          '- Cut through on "human friction"',
          '</english_script>',
          '',
          '# 6-SECOND PREVIEW (ENGLISH)',
          '<preview_english>',
          '"Capital demands speed. [0.5s pause] EtherAgent OS automates your closes in milliseconds."',
          '- KEY MOMENT: Slow, deliberate blink during pause [0.5s]',
          '</preview_english>',
          '',
          '# BRANDING OVERLAY',
          '- Emerald reflection crossing the background glass (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/enterprise (appears 15.0s-18.0s)'
        ]
      },
      {
        id: 'marcus_phase_4',
        title: 'Phase 4: The EtherClaw Master Payload',
        titleEn: 'Phase 4: The EtherClaw Master Payload',
        status: 'completed',
        icon: iconMap.FileText,
        description: 'Genera el payload maestro final compilando todos los activos para renderizado enterprise',
        descriptionEn: 'Generate final master payload compiling all assets for enterprise rendering',
        details: [
          '# COMPILER SYSTEM',
          '{',
          '  "system": "EtherAgent_Enterprise_Compiler",',
          '  "target_niche": "Global_FinTech",',
          '  "instance_type": "Enterprise_HighTicket",',
          '',
          '  "visual_seed": {',
          '    "base_prompt": "[Phase 1 Output]",',
          '    "brand_color_hex": "#10B981",',
          '    "rim_light_fidelity": "strict"',
          '  },',
          '',
          '  "audio_seed": {',
          '    "voice_model": "EtherClaw_V3_Enterprise",',
          '    "languages": ["es-ES", "en-US"],',
          '    "scripts": {',
          '      "spanish": "[Phase 3ES Output]",',
          '      "english": "[Phase 3EN Output]"',
          '    }',
          '  },',
          '',
          '  "motion_seed": {',
          '    "kinesics_profile": "Institutional_Power",',
          '    "facial_expressions": "[Phase 2 Output]",',
          '    "motion_directive": "Zero_movement_except_eyes_and_lips"',
          '  },',
          '',
          '  "compiler_directives": [',
          '    "Enforce zero-blink dominance throughout",',
          '    "Maintain emerald rim light fidelity throughout",',
          '    "Project cold calculation in every frame",',
          '    "Corporate boardroom aesthetic mandatory",',
          '    "Render at minimum 30fps for smooth playback"',
          '  ],',
          '',
          '  "output_config": {',
          '    "formats": ["mp4", "webm"],',
          '    "resolutions": ["1080p", "4k"],',
          '    "aspect_ratios": ["9:16", "4:5", "1:1"]',
          '  }',
          '}',
          '',
          '# RENDER PRIORITY',
          '- Primary: 9:16 (Vertical/Stories - LinkedIn)',
          '- Secondary: 4:5 (Feed/Instagram)',
          '- Tertiary: 1:1 (Square)',
          '',
          '# DEPLOYMENT TARGETS',
          '- etheragent.io/enterprise (CTA principal)',
          '- Social media: LinkedIn (primary), Instagram, YouTube Shorts',
          '- Email marketing: Enterprise ABM sequences',
          '- Sales decks: Executive presentations'
        ]
      }
    ],
    media: {
      avatar_hq: '/assets/images/marcus_hq.webp',
      video_preview_es: '/assets/videos/marcus_6s_es.mp4',
      video_preview_en: '/assets/videos/marcus_6s_en.mp4',
      video_full_es: '/assets/videos/marcus_18s_es.mp4',
      video_full_en: '/assets/videos/marcus_18s_en.mp4'
    }
  },
  {
    id: 'f_elena',
    title: 'Elena R.',
    tag: 'TECH',
    headerLabel: 'AI Founder',
    icon: iconMap.Brain,
    description: 'Founder de startup tech para contenido sobre IA - Nicho SaaS/Tech',
    steps: [
      {
        id: 'elena_phase_1',
        title: 'Phase 1: Hyper-Realistic Image Synthesis',
        titleEn: 'Phase 1: Hyper-Realistic Image Synthesis',
        status: 'completed',
        icon: iconMap.Brain,
        description: 'Genera imagen base de la founder tech con especificaciones exactas para nicho SaaS',
        descriptionEn: 'Generate base image of the tech founder with exact specifications for SaaS niche',
        details: [
          '<subject_lock> Female, 28-32 years old, Mediterranean descent, highly intelligent and sharp gaze, radiating startup founder authority. Her name is Elena R., EtherAI Influencer, SaaS founder archetype. </subject_lock>',
          '<attire> Smart-casual tech chic. Off-white tailored blazer over a dark high-neck top. Minimalist premium aesthetic. Subtle "EtherAI Influencer" embossed in ultra-fine matte silver threading on the left lapel, barely visible, high-end luxury finish. NO logos on clothing except subtle "EtherAI Influencer" brand mark. </attire>',
          '<background> Absolute minimalism. A solid, seamless dark charcoal/pure black studio backdrop. Zero distractions, empty void. </background>',
          '<lighting> Dramatic studio chiaroscuro. Key light: Soft 45-degree diffused white illuminating the face. Rim light: Sharp, vibrant Emerald Green (#10B981) edge light hitting the right shoulder and hair edge, separating the subject from the dark void to anchor the EtherAgent brand identity. </lighting>',
          '<camera_specs> Shot on ARRI Alexa 65, 85mm portrait lens. Razor-sharp focus on the eyes. </camera_specs>',
          '<texture_fidelity> Hyper-detailed skin pores, micro-imperfections, highly realistic skin specular reflection. </texture_fidelity>',
          '<negative_prompt> 3d render, CGI, plastic, cartoon, windows, office, furniture, glass walls, tech incubator, casual clothing, text on clothing, watermarks, red lighting. </negative_prompt>'
        ]
      },
      {
        id: 'elena_phase_2',
        title: 'Phase 2: Neural Motion & Kinesics',
        titleEn: 'Phase 2: Neural Motion & Kinesics',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura movimientos corporales y expresiones faciales para proyectar superioridad algorítmica',
        descriptionEn: 'Configure body movements and facial expressions to project algorithmic superiority',
        details: [
          '# MOTION BASE STATE',
          '<motion_vectors>',
          '- Base state: High confidence, moderada Movement',
          '- Anchor head at center frame',
          '- Limit horizontal sway to ±8 degrees',
          '- Subtle head tilts when making key points',
          '- Energy: Vibrante pero controlada',
          '</motion_vectors>',
          '',
          '# FACIAL EXPRESSIONS',
          '<facial_expressions>',
          '- Action 1: Subtle knowing smile at "algoritmo" to project superiority (00:10)',
          '- Action 2: Slight eyebrow raise on "24/7" for emphasis',
          '- Action 3: Confident nod on "backend" to show technical understanding',
          '- Action 4: Micro-expression of "I know something you don\'t"',
          '- Eye contact: Confident, magnetic, ligeramente quicker blinks',
          '</facial_expressions>',
          '',
          '# KINESICS GUIDELINES',
          '- Eye contact: Magnetic, confident, "sabe un secreto"',
          '- Gestures: Light, purposeful, upper body movement OK',
          '- Posture: Open, approachable but authoritative',
          '- Energy: Silicon Valley startup founder vibe'
        ]
      },
      {
        id: 'elena_phase_3_es',
        title: 'Phase 3: Spanish Audio & Lip-Sync',
        titleEn: 'Phase 3: Spanish Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en español para mercado Latino',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in Spanish for Latin market',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (SaaS Founder Mapping ES) </engine>',
          '<voice_profile>',
          '- Tone: Brillante, persuasiva, empática pero directa',
          '- Pace: 150-160 WPM (energética,硅谷 vibe)',
          '- Accent: Neutral Spanish con slight American influence',
          '- Emotion: Brillante, persuasiva, élite de Silicon Valley',
          '</voice_profile>',
          '',
          '# SPANISH SCRIPT (FULL 18s)',
          '<spanish_script>',
          '[00:00-00:04] APERTURA - Tono empático pero directo',
          '"Construiste un producto increíble, pero nadie lo conoce. [0.3s pause] Típico cuello de botella."',
          '',
          '[00:04-00:09] EL DOLOR - Cejas ligeramente levantadas',
          '"No puedes dividir tu tiempo entre escribir código y prospectar clientes en frío."',
          '',
          '[00:09-00:15] LA SOLUCIÓN - Sonrisa corporativa ganadora',
          '"Deja que mi algoritmo lo haga. [0.3s pause] Estoy impulsada por EtherAgent OS, tu embajadora sintética que no duerme, 24/7."',
          '',
          '[00:15-00:18] CIERRE - Firmeza absoluta',
          '"Tú enfócate en el backend. Yo me encargo del capital."',
          '',
          '# PHONEME FOCUS',
          '- Emphasis on: "producto increíble", "cuello de botella", "algoritmo"',
          '- Smooth delivery on "embajadora sintética"',
          '- Cut through on "24/7"',
          '</spanish_script>',
          '',
          '# 6-SECOND PREVIEW (SPANISH)',
          '<preview_spanish>',
          '"Escalar tu SaaS es un problema matemático. [0.5s pause] EtherAgent OS es la ecuación resuelta."',
          '- KEY MOMENT: Micro-asentimiento al decir "ecuación resuelta"',
          '</preview_spanish>',
          '',
          '# BRANDING OVERLAY',
          '- Destello verde esmeralda sutil en (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/saas (aparece 15.0s-18.0s)'
        ]
      },
      {
        id: 'elena_phase_3_en',
        title: 'Phase 3: English Audio & Lip-Sync',
        titleEn: 'Phase 3: English Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en inglés para mercado USA',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in English for USA market',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (SaaS Founder Mapping EN) </engine>',
          '<voice_profile>',
          '- Tone: Bright, persuasive, empathetic but direct',
          '- Pace: 150-160 WPM (energetic,硅谷 vibe)',
          '- Accent: Neutral American English',
          '- Emotion: Brilliant, persuasive, Silicon Valley elite',
          '</voice_profile>',
          '',
          '# ENGLISH SCRIPT (FULL 18s)',
          '<english_script>',
          '[00:00-00:04] OPENING - Empathetic but direct tone',
          '"You built an incredible product, but nobody knows about it. [0.3s pause] Typical bottleneck."',
          '',
          '[00:04-00:09] THE PAIN - Slightly raised eyebrows',
          '"You can\'t split your time between writing code and prospecting cold clients."',
          '',
          '[00:09-00:15] THE SOLUTION - Winning corporate smile',
          '"Let my algorithm handle it. [0.3s pause] I\'m powered by EtherAgent OS, your synthetic ambassador that doesn\'t sleep, 24/7."',
          '',
          '[00:15-00:18] CLOSURE - Absolute firmness',
          '"You focus on the backend. I\'ll handle the capital."',
          '',
          '# PHONEME FOCUS',
          '- Emphasis on: "incredible product", "bottleneck", "algorithm"',
          '- Smooth delivery on "synthetic ambassador"',
          '- Cut through on "24/7"',
          '</english_script>',
          '',
          '# 6-SECOND PREVIEW (ENGLISH)',
          '<preview_english>',
          '"Scaling your SaaS is a math problem. [0.5s pause] EtherAgent OS is the solved equation."',
          '- KEY MOMENT: Micro-nod at "solved equation"',
          '</preview_english>',
          '',
          '# BRANDING OVERLAY',
          '- Subtle emerald green flash at (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/saas (appears 15.0s-18.0s)'
        ]
      },
      {
        id: 'elena_phase_4',
        title: 'Phase 4: The EtherClaw Master Payload',
        titleEn: 'Phase 4: The EtherClaw Master Payload',
        status: 'completed',
        icon: iconMap.FileText,
        description: 'Genera el payload maestro final compilando todos los activos para renderizado SaaS',
        descriptionEn: 'Generate final master payload compiling all assets for SaaS rendering',
        details: [
          '# COMPILER SYSTEM',
          '{',
          '  "system": "EtherAgent_SaaS_Compiler",',
          '  "target_niche": "USA_Tech_SaaS",',
          '  "instance_type": "Tech_Founder_SaaS",',
          '',
          '  "visual_seed": {',
          '    "base_prompt": "[Phase 1 Output]",',
          '    "brand_color_hex": "#10B981",',
          '    "rim_light_fidelity": "strict"',
          '  },',
          '',
          '  "audio_seed": {',
          '    "voice_model": "EtherClaw_V3_SaaS",',
          '    "languages": ["es-ES", "en-US"],',
          '    "scripts": {',
          '      "spanish": "[Phase 3ES Output]",',
          '      "english": "[Phase 3EN Output]"',
          '    }',
          '  },',
          '',
          '  "motion_seed": {',
          '    "kinesics_profile": "Startup_Founder",',
          '    "facial_expressions": "[Phase 2 Output]",',
          '    "motion_directive": "Confident_energy_with_purpose"',
          '  },',
          '',
          '  "compiler_directives": [',
          '    "Maintain knowing smile authenticity",',
          '    "Project algorithmic superiority throughout",',
          '    "Preserve startup founder energy",',
          '    "Tech incubator aesthetic mandatory",',
          '    "Render at minimum 30fps for smooth playback"',
          '  ],',
          '',
          '  "output_config": {',
          '    "formats": ["mp4", "webm"],',
          '    "resolutions": ["1080p", "4k"],',
          '    "aspect_ratios": ["9:16", "4:5", "1:1"]',
          '  }',
          '}',
          '',
          '# RENDER PRIORITY',
          '- Primary: 9:16 (Vertical/Stories - Instagram/TikTok)',
          '- Secondary: 4:5 (Feed/Instagram)',
          '- Tertiary: 1:1 (Square)',
          '',
          '# DEPLOYMENT TARGETS',
          '- etheragent.io/saas (CTA principal)',
          '- Social media: Instagram (primary), LinkedIn, TikTok, YouTube Shorts',
          '- Email marketing: SaaS founder nurturing sequences',
          '- Product launches: Demo videos, feature announcements'
        ]
      }
    ],
    media: {
      avatar_hq: '/assets/images/elena_hq.webp',
      video_preview_es: '/assets/videos/elena_6s_es.mp4',
      video_preview_en: '/assets/videos/elena_6s_en.mp4',
      video_full_es: '/assets/videos/elena_18s_es.mp4',
      video_full_en: '/assets/videos/elena_18s_en.mp4'
    }
  },
  {
    id: 'f_aris',
    title: 'Dr. Aris',
    tag: 'MEDTECH',
    headerLabel: 'Medical Specialist',
    icon: iconMap.Brain,
    description: 'Especialista médico europeo para contenido de salud',
    steps: [
      {
        id: 'aris_phase_1',
        title: 'Phase 1: Hyper-Realistic Image Synthesis',
        titleEn: 'Phase 1: Hyper-Realistic Image Synthesis',
        status: 'completed',
        icon: iconMap.Brain,
        description: 'Genera imagen base del especialista médico',
        descriptionEn: 'Generate base image of the medical specialist',
        details: [
          '<subject_lock> Male, 45-50 years old, European descent, distinguished silver-fox hair, warm but highly authoritative gaze. His name is Dr. Aris, EtherAI Influencer, medical specialist archetype. </subject_lock>',
          '<attire> Premium tailored white lab coat over a dark navy blue dress shirt. Subtle "EtherAI Influencer" embossed in ultra-fine matte silver threading on the left chest pocket area, barely visible, high-end luxury finish. NO logos on clothing except subtle "EtherAI Influencer" brand mark. </attire>',
          '<background> Absolute minimalism. A solid, seamless dark charcoal/pure black studio backdrop. Zero distractions, empty void. </background>',
          '<lighting> Dramatic studio chiaroscuro. Key light: Soft 45-degree diffused white illuminating the face. Rim light: Sharp, vibrant Emerald Green (#10B981) edge light hitting the left shoulder, separating the subject from the dark void to anchor the EtherAgent brand identity. </lighting>',
          '<camera_specs> Shot on ARRI Alexa 65, 85mm portrait lens. Razor-sharp focus on the eyes. </camera_specs>',
          '<texture_fidelity> Hyper-detailed skin pores, micro-imperfections, highly realistic skin specular reflection. </texture_fidelity>',
          '<negative_prompt> 3d render, CGI, plastic, cartoon, windows, office, furniture, clinical laboratory, lab equipment, casual clothing, text on clothing, watermarks. </negative_prompt>'
        ]
      },
      {
        id: 'aris_phase_2',
        title: 'Phase 2: Neural Motion & Kinesics',
        titleEn: 'Phase 2: Neural Motion & Kinesics',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura movimientos y expresiones faciales neurales',
        descriptionEn: 'Configure neural movements and facial expressions',
        details: [
          '# MOTION BASE STATE',
          '<motion_vectors>',
          '- Base state: Calm, reassuring authority',
          '- Anchor head at center frame',
          '- Minimal horizontal sway (±3 degrees)',
          '- Subtle breathing (4s cycle for gravitas)',
          '- Weight shift: None - projected stability',
          '</motion_vectors>',
          '',
          '# FACIAL EXPRESSIONS',
          '<facial_expressions>',
          '- Action 1: Subtle confident nod at 00:02 to project medical authority',
          '- Action 2: Warm but authoritative expression maintained throughout',
          '- Action 3: Gentle micro-smile when mentioning patient care',
          '- Eye contact: Warm, trustworthy, empathetic',
          '- Blinking rate: Natural, 4-5 per minute',
          '</facial_expressions>',
          '',
          '# KINESICS GUIDELINES',
          '- Eye contact: Warm but authoritative',
          '- Gestures: Minimal, purposeful, confined to lower third of frame',
          '- Posture: Straight, professional, approachable authority',
          '- Movement: Calm, deliberate, reassuring'
        ]
      },
      {
        id: 'aris_phase_3_es',
        title: 'Phase 3: Spanish Audio & Lip-Sync',
        titleEn: 'Phase 3: Spanish Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en español',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in Spanish',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Medical Authority Mapping ES) </engine>',
          '<voice_profile>',
          '- Tone: Warm, authoritative, reassuring but professional',
          '- Pace: 135-145 WPM (calm, measured delivery)',
          '- Accent: Neutral Spanish (European/Latin American)',
          '- Emotion: Trustworthy, knowledgeable, caring professional',
          '</voice_profile>',
          '',
          '# SPANISH SCRIPT (FULL 18s)',
          '<spanish_script>',
          '[00:00-00:04] APERTURA - Tono empático y profesional',
          '"La medicina del futuro no espera. [0.3s pause] Los pacientes merecen lo mejor."',
          '',
          '[00:04-00:09] EL DOLOR - Análisis静 (tono analítico)',
          '"Las clínicas tradicionales pierden eficiencia. El tiempo médico es oro."',
          '',
          '[00:09-00:15] LA SOLUCIÓN - Tono expansivo y seguro',
          '"EtherAgent OS optimiza tu práctica. [0.3s pause] Automatiza administrativas, maximiza atención al paciente."',
          '',
          '[00:15-00:18] CIERRE - Llamada a acción profesional',
          '"Escala tu impacto médico. Tu próxima generación de pacientes te lo agradecerá."',
          '',
          '# PHONEME FOCUS',
          '- Emphasis on: "medicina del futuro", "eficiencia", "tiempo médico"',
          '- Smooth delivery on "pacientes merecen lo mejor"',
          '- Cut through on "automatiza administrativas"',
          '</spanish_script>',
          '',
          '# 6-SECOND PREVIEW (SPANISH)',
          '<preview_spanish>',
          '"La salud no espera. [0.5s pause] EtherAgent OS optimiza tu clínica en tiempo real."',
          '- KEY MOMENT: Confident nod at "optimiza tu clínica"',
          '</preview_spanish>',
          '',
          '# BRANDING OVERLAY',
          '- Emerald green pulse subtle at (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/health (aparece 15.0s-18.0s)'
        ]
      },
      {
        id: 'aris_phase_3_en',
        title: 'Phase 3: English Audio & Lip-Sync',
        titleEn: 'Phase 3: English Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en inglés',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in English',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Medical Authority Mapping EN) </engine>',
          '<voice_profile>',
          '- Tone: Warm, authoritative, reassuring but professional',
          '- Pace: 135-145 WPM (calm, measured delivery)',
          '- Accent: Neutral American English',
          '- Emotion: Trustworthy, knowledgeable, caring professional',
          '</voice_profile>',
          '',
          '# ENGLISH SCRIPT (FULL 18s)',
          '<english_script>',
          '[00:00-00:04] OPENING - Empathetic and professional tone',
          '"The medicine of the future doesn\'t wait. [0.3s pause] Patients deserve the best."',
          '',
          '[00:04-00:09] THE PAIN - Analytical tone',
          '"Traditional clinics lose efficiency. Medical time is gold."',
          '',
          '[00:09-00:15] THE SOLUTION - Expansive and confident tone',
          '"EtherAgent OS optimizes your practice. [0.3s pause] Automates admin work, maximizes patient attention."',
          '',
          '[00:15-00:18] CLOSURE - Professional Call to Action',
          '"Scale your medical impact. Your next generation of patients will thank you."',
          '',
          '# PHONEME FOCUS',
          '- Emphasis on: "medicine of the future", "efficiency", "medical time"',
          '- Smooth delivery on "patients deserve the best"',
          '- Cut through on "automates admin work"',
          '</english_script>',
          '',
          '# 6-SECOND PREVIEW (ENGLISH)',
          '<preview_english>',
          '"Health doesn\'t wait. [0.5s pause] EtherAgent OS optimizes your clinic in real-time."',
          '- KEY MOMENT: Confident nod at "optimizes your clinic"',
          '</preview_english>',
          '',
          '# BRANDING OVERLAY',
          '- Emerald green pulse subtle at (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/health (appears 15.0s-18.0s)'
        ]
      },
      {
        id: 'aris_phase_4',
        title: 'Phase 4: The EtherClaw Master Payload',
        titleEn: 'Phase 4: The EtherClaw Master Payload',
        status: 'completed',
        icon: iconMap.FileText,
        description: 'Genera el payload maestro final compilando todos los activos para renderizado médico',
        descriptionEn: 'Generate final master payload compiling all assets for medical rendering',
        details: [
          '# COMPILER SYSTEM',
          '{',
          '  "system": "EtherAgent_Health_Compiler",',
          '  "target_niche": "Europe_MedTech",',
          '  "instance_type": "Medical_Specialist",',
          '',
          '  "visual_seed": {',
          '    "base_prompt": "[Phase 1 Output]",',
          '    "brand_color_hex": "#10B981",',
          '    "rim_light_fidelity": "strict"',
          '  },',
          '',
          '  "audio_seed": {',
          '    "voice_model": "EtherClaw_V3_Medical",',
          '    "languages": ["es-ES", "en-US"],',
          '    "scripts": {',
          '      "spanish": "[Phase 3ES Output]",',
          '      "english": "[Phase 3EN Output]"',
          '    }',
          '  },',
          '',
          '  "motion_seed": {',
          '    "kinesics_profile": "Medical_Authority",',
          '    "facial_expressions": "[Phase 2 Output]",',
          '    "motion_directive": "Calm_reassuring_professional"',
          '  },',
          '',
          '  "compiler_directives": [',
          '    "Maintain warm but authoritative presence throughout",',
          '    "Project medical trust in every frame",',
          '    "Preserve clinical professionalism aesthetic",',
          '    "Render at minimum 30fps for smooth playback"',
          '  ],',
          '',
          '  "output_config": {',
          '    "formats": ["mp4", "webm"],',
          '    "resolutions": ["1080p", "4k"],',
          '    "aspect_ratios": ["9:16", "4:5", "1:1"]',
          '  }',
          '}',
          '',
          '# RENDER PRIORITY',
          '- Primary: 9:16 (Vertical/Stories - LinkedIn)',
          '- Secondary: 4:5 (Feed/Instagram)',
          '- Tertiary: 1:1 (Square)',
          '',
          '# DEPLOYMENT TARGETS',
          '- etheragent.io/health (CTA principal)',
          '- Social media: LinkedIn (primary), Instagram, YouTube Shorts',
          '- Email marketing: Medical professional nurturing sequences',
          '- Healthcare conferences: Presentation videos'
        ]
      }
    ],
    media: {
      avatar_hq: '/assets/images/aris_hq.webp',
      video_preview_es: '/assets/videos/aris_6s_es.mp4',
      video_preview_en: '/assets/videos/aris_6s_en.mp4',
      video_full_es: '/assets/videos/aris_18s_es.mp4',
      video_full_en: '/assets/videos/aris_18s_en.mp4'
    }
  },
  {
    id: 'f_viktor',
    title: 'Viktor S.',
    tag: 'E-COMMERCE',
    headerLabel: 'E-commerce Growth Architect',
    icon: iconMap.Brain,
    description: 'Arquitecto de crecimiento para E-commerce y D2C Brands',
    steps: [
      {
        id: 'viktor_phase_1',
        title: 'Phase 1: Hyper-Realistic Image Synthesis',
        titleEn: 'Phase 1: Hyper-Realistic Image Synthesis',
        status: 'completed',
        icon: iconMap.Brain,
        description: 'Genera imagen base del arquitecto de crecimiento E-commerce',
        descriptionEn: 'Generate base image of the E-commerce growth architect',
        details: [
          '<subject_lock> Male, 28-32 years old, Eastern European descent, intense analytical gaze, sharp cheekbones, modern styled textured haircut. His name is Viktor S., EtherAI Influencer, E-commerce Growth archetype. </subject_lock>',
          '<attire> Modern luxury streetwear. Premium heavyweight oversized hoodie in deep charcoal. Subtle "EtherAI Influencer" embossed in ultra-fine matte silver threading on the left chest, high-end stealth wealth finish. NO other logos. </attire>',
          '<background> Absolute minimalism. A solid, seamless dark charcoal/pure black studio backdrop. Zero distractions, empty void. </background>',
          '<lighting> Dramatic studio chiaroscuro. Key light: High-contrast 45-degree white. Rim light: Piercing, vibrant Emerald Green (#10B981) edge light hitting the left shoulder and hood edge, separating the subject from the dark void to anchor the EtherAgent brand. </lighting>',
          '<camera_specs> Shot on ARRI Alexa 65, 50mm Master Prime lens. Aggressive, slightly lower angle to project dominance. </camera_specs>',
          '<texture_fidelity> Hyper-detailed fabric texture, micro-imperfections on skin, sharp pupil catchlights reflecting a monitor glow. </texture_fidelity>',
          '<negative_prompt> 3d render, CGI, plastic, cartoon, windows, office, messy background, large text, watermarks, smiling widely. </negative_prompt>'
        ]
      },
      {
        id: 'viktor_phase_2',
        title: 'Phase 2: Neural Motion & Kinesics',
        titleEn: 'Phase 2: Neural Motion & Kinesics',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura movimientos corporales y expresiones faciales para proyectar dominio analítico',
        descriptionEn: 'Configure body movements and facial expressions to project analytical dominance',
        details: [
          '<motion_vectors> Aggressive forward lean. High-energy base state. </motion_vectors>',
          '<facial_expressions> Action 1: Intense, unbroken eye contact. Piercing look at 00:04 when discussing revenue loss. </facial_expressions>'
        ]
      },
      {
        id: 'viktor_phase_3_es',
        title: 'Phase 3: Spanish Audio & Lip-Sync',
        titleEn: 'Phase 3: Spanish Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en español',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in Spanish',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (E-commerce Growth Mapping ES) </engine>',
          '<voice_profile>',
          '- Tone: Urgente, disruptivo, analítico - autoridad de crecimiento',
          '- Pace: 155-165 WPM (rápido, energético)',
          '- Accent: Neutral Spanish',
          '- Emotion: Urgente, authoritative, Growth Hacker',
          '</voice_profile>',
          '',
          '# SPANISH SCRIPT (FULL 18s)',
          '<spanish_script>',
          '[00:00-00:04] APERTURA - Tono urgente',
          '"Estás quemando presupuesto en anuncios de Meta y TikTok para adquirir tráfico vacío."',
          '',
          '[00:04-00:08] EL DOLOR - Análisis cortante',
          '"El verdadero margen del E-commerce está en el backend, y tú lo estás ignorando."',
          '',
          '[00:08-00:14] LA SOLUCIÓN - Expansivo y seguro',
          '"EtherAgent OS analiza el comportamiento de tus usuarios y lanza micro-campañas de retención ultra-personalizadas en tiempo real."',
          '',
          '[00:14-00:18] CIERRE - Call to Action definitivo',
          '"Deja de comprar clics. Empieza a construir LTV. Instala EtherAgent."',
          '',
          '# PHONEME FOCUS',
          '- Sharp emphasis on: "quemando presupuesto", "backend", "LTV"',
          '- Cut through on "micro-campañas de retención"',
          '</spanish_script>',
          '',
          '# 6-SECOND PREVIEW (SPANISH)',
          '<preview_spanish>',
          'Text: "El ROAS está muerto si tu retención es cero. [0.5s pause] EtherAgent OS recupera tus carritos abandonados al instante."',
          'Duration: 6.0s. Emotion: Urgente, disruptivo.',
          '</preview_spanish>',
          '',
          '# BRANDING OVERLAY',
          '- Logo #10B981 latido sutil en el fondo (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/ecommerce (aparece 15.0s-18.0s)'
        ]
      },
      {
        id: 'viktor_phase_3_en',
        title: 'Phase 3: English Audio & Lip-Sync',
        titleEn: 'Phase 3: English Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en inglés',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in English',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (E-commerce Growth Mapping EN) </engine>',
          '<voice_profile>',
          '- Tone: Urgent, disruptive, analytical - growth authority',
          '- Pace: 155-165 WPM (fast, energetic)',
          '- Accent: Neutral American English',
          '- Emotion: Urgent, authoritative, Growth Hacker',
          '</voice_profile>',
          '',
          '# ENGLISH SCRIPT (FULL 18s)',
          '<english_script>',
          '[00:00-00:04] OPENING - Urgent tone',
          '"You\'re burning budget on Meta and TikTok ads to acquire empty traffic."',
          '',
          '[00:04-00:08] THE PAIN - Cutting analysis',
          '"The real margin in E-commerce is in the backend, and you\'re ignoring it."',
          '',
          '[00:08-00:14] THE SOLUTION - Expansive and confident',
          '"EtherAgent OS analyzes your user behavior and launches ultra-personalized retention micro-campaigns in real-time."',
          '',
          '[00:14-00:18] CLOSURE - Definitive Call to Action',
          '"Stop buying clicks. Start building LTV. Install EtherAgent."',
          '',
          '# PHONEME FOCUS',
          '- Sharp emphasis on: "burning budget", "backend", "LTV"',
          '- Cut through on "ultra-personalized retention"',
          '</english_script>',
          '',
          '# 6-SECOND PREVIEW (ENGLISH)',
          '<preview_english>',
          'Text: "ROAS is dead if your retention is zero. [0.5s pause] EtherAgent OS recovers your abandoned carts instantly."',
          'Duration: 6.0s. Emotion: Urgent, authoritative.',
          '</preview_english>',
          '',
          '# BRANDING OVERLAY',
          '- Logo #10B981 subtle pulse in background (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/ecommerce (appears 15.0s-18.0s)'
        ]
      },
      {
        id: 'viktor_phase_4',
        title: 'Phase 4: The EtherClaw Master Payload',
        titleEn: 'Phase 4: The EtherClaw Master Payload',
        status: 'completed',
        icon: iconMap.FileText,
        description: 'Genera el payload maestro final compilando todos los activos para renderizado E-commerce',
        descriptionEn: 'Generate final master payload compiling all assets for E-commerce rendering',
        details: [
          '# COMPILER SYSTEM',
          '{',
          '  "system": "EtherAgent_Ecommerce_Compiler",',
          '  "target_niche": "Global_D2C_Brands",',
          '  "instance_type": "Ecommerce_Growth_Architect",',
          '',
          '  "visual_seed": {',
          '    "base_prompt": "[Phase 1 Output]",',
          '    "brand_color_hex": "#10B981",',
          '    "rim_light_fidelity": "strict"',
          '  },',
          '',
          '  "audio_seed": {',
          '    "voice_model": "EtherClaw_V3_Ecommerce",',
          '    "languages": ["es-ES", "en-US"],',
          '    "scripts": {',
          '      "spanish": "[Phase 3ES Output]",',
          '      "english": "[Phase 3EN Output]"',
          '    }',
          '  },',
          '',
          '  "motion_seed": {',
          '    "kinesics_profile": "Aggressive_Analytical",',
          '    "facial_expressions": "[Phase 2 Output]",',
          '    "motion_directive": "Forward_lean_energy"',
          '  },',
          '',
          '  "compiler_directives": [',
          '    "Enforce aggressive analytical posture",',
          '    "Maximize audio clarity for fast pacing",',
          '    "Maintain emerald rim light fidelity throughout",',
          '    "Preserve growth hacker energy",',
          '    "Render at minimum 30fps for smooth playback"',
          '  ],',
          '',
          '  "output_config": {',
          '    "formats": ["mp4", "webm"],',
          '    "resolutions": ["1080p", "4k"],',
          '    "aspect_ratios": ["9:16", "4:5", "1:1"]',
          '  }',
          '}',
          '',
          '# RENDER PRIORITY',
          '- Primary: 9:16 (Vertical/Stories - TikTok/Instagram)',
          '- Secondary: 4:5 (Feed/Instagram)',
          '- Tertiary: 1:1 (Square)',
          '',
          '# DEPLOYMENT TARGETS',
          '- etheragent.io/ecommerce (CTA principal)',
          '- Social media: TikTok (primary), Instagram, YouTube Shorts, LinkedIn',
          '- Email marketing: D2C retention sequences',
          '- Ad campaigns: High-velocity conversion funnels'
        ]
      }
    ],
    media: {
      avatar_hq: '/assets/images/viktor_hq.webp',
      video_preview_es: '/assets/videos/viktor_6s_es.mp4',
      video_preview_en: '/assets/videos/viktor_6s_en.mp4',
      video_full_es: '/assets/videos/viktor_18s_es.mp4',
      video_full_en: '/assets/videos/viktor_18s_en.mp4'
    }
  },
  {
    id: 'f_valeria_sdr',
    title: 'Valeria M.',
    tag: 'AGENCIES',
    headerLabel: 'Growth Strategist & B2B Closer',
    icon: iconMap.Brain,
    description: 'La Closer de Agencias - Instancia SDR optimizada para prospección B2B en LATAM',
    steps: [
      {
        id: 'valeria_phase_1',
        title: 'Phase 1: Hyper-Realistic Image Synthesis',
        titleEn: 'Phase 1: Hyper-Realistic Image Synthesis',
        status: 'completed',
        icon: iconMap.Brain,
        description: 'Genera imagen base de la Closer de Agencias',
        descriptionEn: 'Generate base image of the Agency Closer',
        details: [
          '<subject_lock> Female, 24-27 years old, Latina descent, bright engaging eyes, welcoming but sharp half-smile, projecting dynamic energy. Her name is Valeria M., EtherAI Influencer, Dynamic SDR archetype. </subject_lock>',
          '<attire> Modern creative agency aesthetic. Premium soft terracotta blazer over a crisp dark tee. Subtle "EtherAI Influencer" embossed in ultra-fine matte silver threading on the lapel, barely visible, high-end luxury finish. NO other logos. </attire>',
          '<background> Absolute minimalism. A solid, seamless dark charcoal/pure black studio backdrop. Zero distractions, empty void. </background>',
          '<lighting> Dramatic studio chiaroscuro. Key light: Soft 45-degree diffused white illuminating the face warmly. Rim light: Sharp, vibrant Emerald Green (#10B981) edge light hitting the right shoulder, separating the subject from the dark void to anchor the EtherAgent brand identity. </lighting>',
          '<camera_specs> Shot on ARRI Alexa 65, 85mm portrait lens. Razor-sharp focus on the eyes, flattering depth of field. </camera_specs>',
          '<texture_fidelity> Hyper-detailed skin pores, micro-imperfections, highly realistic skin specular reflection. </texture_fidelity>',
          '<negative_prompt> 3d render, CGI, plastic, cartoon, windows, office, furniture, messy background, large text, watermarks, unprofessional. </negative_prompt>'
        ]
      },
      {
        id: 'valeria_phase_2',
        title: 'Phase 2: Neural Motion & Kinesics',
        titleEn: 'Phase 2: Neural Motion & Kinesics',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura movimientos corporales y expresiones faciales para proyectar empatía dinámica',
        descriptionEn: 'Configure body movements and facial expressions to project dynamic empathy',
        details: [
          '<motion_vectors> Active listening simulation. Fluid, conversational head movements. Occasional 5-degree head tilt to project deep empathy. </motion_vectors>',
          '<facial_expressions> Base state: Welcoming warmth. Action 1: Slight eyebrow raise at 00:03 to emphasize a client pain point (e.g., lost leads). </facial_expressions>'
        ]
      },
      {
        id: 'valeria_phase_3_es',
        title: 'Phase 3: Spanish Audio & Lip-Sync',
        titleEn: 'Phase 3: Spanish Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en español',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in Spanish',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Agency SDR Mapping ES) </engine>',
          '<voice_profile>',
          '- Tone: Consultiva, resolutiva, dinámica - empatía activa',
          '- Pace: 145-155 WPM (energética, natural)',
          '- Accent: Neutral Latin American Spanish',
          '- Emotion: Consultiva, resolutiva, empática',
          '</voice_profile>',
          '',
          '# SPANISH SCRIPT (FULL 18s)',
          '<spanish_script>',
          '[00:00-00:04] APERTURA - Tono cálido pero directo',
          '"Hola. He auditado los embudos de más de 500 agencias de marketing este mes."',
          '',
          '[00:04-00:09] EL DOLOR - Empatía activa',
          '"El 80% de sus leads se enfrían porque sus SDRs humanos tardan horas en responder."',
          '',
          '[00:09-00:14] LA SOLUCIÓN - Firme y resolutiva',
          '"Soy Valeria. Opero bajo la infraestructura de EtherAgent OS. Respondo, califico y agendo en 3 segundos."',
          '',
          '[00:14-00:18] CIERRE - Call to Action definitivo',
          '"Sella tus fugas de capital. Despliega tu primer agente hoy."',
          '',
          '# PHONEME FOCUS',
          '- Emphasis on: "embudos", "leads se enfrían", "respondo, califico y agendo"',
          '- Warm delivery on "Soy Valeria"',
          '- Cut through on "fugas de capital"',
          '</spanish_script>',
          '',
          '# 6-SECOND PREVIEW (SPANISH)',
          '<preview_spanish>',
          'Text: "Tu agencia pierde clientes por seguimientos lentos. [0.5s pause] EtherAgent OS agenda reuniones mientras tú duermes."',
          'Duration: 6.0s. Emotion: Consultiva, resolutiva.',
          '</preview_spanish>',
          '',
          '# BRANDING OVERLAY',
          '- Logo #10B981 latido sutil en el fondo (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/agencies (aparece 15.0s-18.0s)'
        ]
      },
      {
        id: 'valeria_phase_3_en',
        title: 'Phase 3: English Audio & Lip-Sync',
        titleEn: 'Phase 3: English Audio & Lip-Sync',
        status: 'completed',
        icon: iconMap.Radio,
        description: 'Configura síntesis de voz profesional y mapeo de labios en inglés',
        descriptionEn: 'Configure professional voice synthesis and lip-sync mapping in English',
        details: [
          '# VOICE ENGINE',
          '<engine> EtherClaw Neural Voice V3 (Agency SDR Mapping EN) </engine>',
          '<voice_profile>',
          '- Tone: Consultative, resolutive, dynamic - active empathy',
          '- Pace: 145-155 WPM (energetic, natural)',
          '- Accent: Neutral American English',
          '- Emotion: Consultative, resolutive, empathetic',
          '</voice_profile>',
          '',
          '# ENGLISH SCRIPT (FULL 18s)',
          '<english_script>',
          '[00:00-00:04] OPENING - Warm but direct tone',
          '"Hello. I\'ve audited the funnels of over 500 marketing agencies this month."',
          '',
          '[00:04-00:09] THE PAIN - Active empathy',
          '"80% of their leads go cold because their human SDRs take hours to respond."',
          '',
          '[00:09-00:14] THE SOLUTION - Firm and resolute',
          '"I\'m Valeria. I operate on the EtherAgent OS infrastructure. I respond, qualify, and book in 3 seconds."',
          '',
          '[00:14-00:18] CLOSURE - Definitive Call to Action',
          '"Seal your capital leaks. Deploy your first agent today."',
          '',
          '# PHONEME FOCUS',
          '- Emphasis on: "funnels", "leads go cold", "respond, qualify, and book"',
          '- Warm delivery on "I\'m Valeria"',
          '- Cut through on "capital leaks"',
          '</english_script>',
          '',
          '# 6-SECOND PREVIEW (ENGLISH)',
          '<preview_english>',
          'Text: "Your agency loses clients to slow follow-ups. [0.5s pause] EtherAgent OS books meetings while you sleep."',
          'Duration: 6.0s. Emotion: Empathetic, high-energy.',
          '</preview_english>',
          '',
          '# BRANDING OVERLAY',
          '- Logo #10B981 subtle pulse in background (5.0s-6.0s / 15.0s-18.0s)',
          '- CTA: etheragent.io/agencies (appears 15.0s-18.0s)'
        ]
      },
      {
        id: 'valeria_phase_4',
        title: 'Phase 4: The EtherClaw Master Payload',
        titleEn: 'Phase 4: The EtherClaw Master Payload',
        status: 'completed',
        icon: iconMap.FileText,
        description: 'Genera el payload maestro final compilando todos los activos para renderizado SDR',
        descriptionEn: 'Generate final master payload compiling all assets for SDR rendering',
        details: [
          '# COMPILER SYSTEM',
          '{',
          '  "system": "EtherAgent_SDR_Compiler",',
          '  "target_niche": "LATAM_Agencies",',
          '  "instance_type": "Agency_Closer_SDR",',
          '',
          '  "visual_seed": {',
          '    "base_prompt": "[Phase 1 Output]",',
          '    "brand_color_hex": "#10B981",',
          '    "rim_light_fidelity": "strict"',
          '  },',
          '',
          '  "audio_seed": {',
          '    "voice_model": "EtherClaw_V3_SDR",',
          '    "languages": ["es-ES", "en-US"],',
          '    "scripts": {',
          '      "spanish": "[Phase 3ES Output]",',
          '      "english": "[Phase 3EN Output]"',
          '    }',
          '  },',
          '',
          '  "motion_seed": {',
          '    "kinesics_profile": "Dynamic_Empathy",',
          '    "facial_expressions": "[Phase 2 Output]",',
          '    "motion_directive": "Active_listening_warmth"',
          '  },',
          '',
          '  "compiler_directives": [',
          '    "Enforce empathetic micro-expressions",',
          '    "Maintain dynamic warmth",',
          '    "Maintain emerald rim light fidelity throughout",',
          '    "Preserve bilingual clarity for both markets",',
          '    "Render at minimum 30fps for smooth playback"',
          '  ],',
          '',
          '  "output_config": {',
          '    "formats": ["mp4", "webm"],',
          '    "resolutions": ["1080p", "4k"],',
          '    "aspect_ratios": ["9:16", "4:5", "1:1"]',
          '  }',
          '}',
          '',
          '# RENDER PRIORITY',
          '- Primary: 9:16 (Vertical/Stories - LinkedIn/Instagram)',
          '- Secondary: 4:5 (Feed/Instagram)',
          '- Tertiary: 1:1 (Square)',
          '',
          '# DEPLOYMENT TARGETS',
          '- etheragent.io/agencies (CTA principal)',
          '- Social media: LinkedIn (primary), Instagram, YouTube Shorts',
          '- Email marketing: Agency SDR sequences',
          '- Outbound campaigns: High-velocity B2B prospecting'
        ]
      }
    ],
    media: {
      avatar_hq: '/assets/images/valeria_hq.webp',
      video_preview_es: '/assets/videos/valeria_6s_es.mp4',
      video_preview_en: '/assets/videos/valeria_6s_en.mp4',
      video_full_es: '/assets/videos/valeria_18s_es.mp4',
      video_full_en: '/assets/videos/valeria_18s_en.mp4'
    }
  }
];

export const mockTelemetry: TelemetryData = {
  revenue: 24750,
  dailyLeads: 47,
  activeRentals: 12,
  topAvatar: 'Dr. Elena Vásquez',
  roas: 4.2
};

export const avatarCategories = [
  { id: 'all', name: 'All Avatars', icon: '🎭' },
  { id: 'healthcare', name: 'Healthcare', icon: '🏥' },
  { id: 'technology', name: 'Technology', icon: '💻' },
  { id: 'finance', name: 'Finance', icon: '💰' },
  { id: 'business', name: 'Business', icon: '💼' },
  { id: 'legal', name: 'Legal', icon: '⚖️' },
  { id: 'education', name: 'Education', icon: '📚' },
  { id: 'health', name: 'Health & Fitness', icon: '💪' }
];

export const templateCategories = [
  { id: 'all', name: 'All Templates', icon: '📋' },
  { id: 'marketing', name: 'Marketing', icon: '📣' },
  { id: 'real estate', name: 'Real Estate', icon: '🏠' },
  { id: 'education', name: 'Education', icon: '🎓' },
  { id: 'healthcare', name: 'Healthcare', icon: '⚕️' },
  { id: 'health', name: 'Health & Fitness', icon: '💪' }
];
